pipeline {
  agent {
    label 'master'
  }
  environment{
    BRANCH = "${params.BRANCH}"
  }
  parameters {
    string(
      name: "BRANCH",
      defaultValue: "master",
      description: "Branch to build the packer job."
    )
    string(
      name: "AMI_TYPE",
      defaultValue: "cis",
      description: "Type of AMI to build"
    )
  }
  stages {
    stage("Sync the code"){
      steps {
          checkout(
                    [   $class: 'GitSCM',
                        branches: [[name: "${params.BRANCH}"]],
                        browser: [$class: 'AssemblaWeb', repoUrl: ''], doGenerateSubmoduleConfigurations: false,
                        extensions: [[
                            $class: 'SubmoduleOption',
                            disableSubmodules: false,
                            parentCredentials: false,
                            recursiveSubmodules: true,
                            reference: '',
                            trackingSubmodules: false]],
                        submoduleCfg: [],
                        userRemoteConfigs: [[
                            url: "https://github.com/abhijitsingamaneni/abhijit_task.git"]]
                    ]
                )
      }
    }
    stage("Execute build"){
      environment{
        AMI_TYPE = "${params.AMI_TYPE}"
        BRANCH = "${params.BRANCH}"
      }
      steps {
          sh 'ls -la'
          dir("jenkins-cis-automation/packer/${params.AMI_TYPE}"){
            echo "Switched dir to jenkins-cis-automation/packer/${params.AMI_TYPE}"
            sh 'ls -la'
            sh 'wget -c https://releases.hashicorp.com/packer/1.1.0/packer_1.1.0_linux_amd64.zip'
            sh 'unzip -o packer_1.1.0_linux_amd64.zip'
            sh 'ls -la'
            sh './packer build -var "ami_target_regions=us-west-2" -var "jenkins_build_id=$BUILD_ID" ./packer.json'
        }
      }
    }
    stage("cleanup workspace"){
      steps {
        deleteDir()
      }
    }
  }
}
