---

- name: sysctl flush ipv4 route table
  sysctl:
      name: net.ipv4.route.flush
      value: 1
      sysctl_set: true

- name: sysctl flush ipv6 route table
  sysctl:
      name: net.ipv6.route.flush
      value: 1
      sysctl_set: true
      ignoreerrors: true

- name: restart auditd
  service:
      name: auditd
      state: restarted
      use: service

- name: load audit rules
  command: /sbin/augenrules --load

- name: generate new grub config ubuntu
  shell: grub-mkconfig -o "{{ grub_cfg.stat.path }}" && chmod 600 /boot/grub/grub.cfg
  when: ansible_distribution == 'Ubuntu' 

- name: generate new grub config centos
  shell: grub2-mkconfig > /boot/grub2/grub.cfg 
  when: ansible_distribution == 'CentOS'

- name: reload systemd
  command: systemctl daemon-reload

- name: restart docker
  service:
      name: docker
      state: restarted

